/**
 * PNG → glasses-BMP converter (build-time util).
 *
 * Pipeline: PNG  --sips-->  88×88 24-bit BMP  -->  8-bit grayscale pixels
 *           -->  encodeBmpBase64()  -->  base64 BMP string the glasses display.
 *
 * PNG is the right SOURCE: it's lossless, so downscaling + graying doesn't
 * fight JPEG artifacts. BMP is the right TARGET: it's what the phone SGC /
 * G2 native side decode (see bmp.ts / convertToG2Bmp).
 *
 * We shell out to macOS `sips` for decode+resize (no npm image deps). It
 * emits a 24-bit, top-down (negative-height) uncompressed BMP with a 54-byte
 * header — easy to parse by hand.
 *
 * Usage:
 *   bun run src/test/bitmaps/png-to-bmp.ts <input.png> [size]
 *   # → writes <input>.bmp.ts exporting the base64 BMP string + dims.
 *
 * Default size is 88 (→ 88×88).
 */

import {$} from "bun"
import {encodeBmpBase64} from "../../background/lib/bmp"

const DEFAULT_SIZE = 88

/**
 * Convert a PNG file to a base64 grayscale BMP at `size`×`size`, ready for
 * a `session.display.render()` image element. Returns the base64 string.
 */
export async function pngToGlassesBmp(pngPath: string, size = DEFAULT_SIZE): Promise<string> {
  const tmpBmp = `/tmp/png-to-bmp-${size}.bmp`

  // Resize to size×size and emit a 24-bit BMP. `-z H W` forces exact dims
  // (not aspect-preserving) — caller asked for a fixed square.
  await $`sips -z ${size} ${size} -s format bmp ${pngPath} --out ${tmpBmp}`.quiet()

  const bmp = new Uint8Array(await Bun.file(tmpBmp).arrayBuffer())

  // --- Parse the BMP sips produced (BITMAPINFOHEADER, 24-bit, uncompressed) ---
  const readU32 = (o: number) => bmp[o] | (bmp[o + 1] << 8) | (bmp[o + 2] << 16) | (bmp[o + 3] << 24)
  const readI32 = (o: number) => readU32(o) | 0

  const pixelOffset = readU32(10)
  const width = readI32(18)
  const rawHeight = readI32(22)
  const topDown = rawHeight < 0
  const height = Math.abs(rawHeight)
  const bpp = bmp[28] | (bmp[29] << 8)

  if (bpp !== 24) throw new Error(`expected 24-bit BMP from sips, got ${bpp}-bit`)

  // 24-bit rows are padded to a 4-byte boundary; pixels are stored B,G,R.
  const rowSize = ((width * 3 + 3) >> 2) << 2

  // Build the 8-bit grayscale buffer encodeBmpBase64 wants: row-major, TOP-DOWN.
  const gray = new Uint8Array(width * height)
  for (let y = 0; y < height; y++) {
    // Map our top-down output row `y` to the source row in the BMP.
    const srcRow = topDown ? y : height - 1 - y
    const rowStart = pixelOffset + srcRow * rowSize
    for (let x = 0; x < width; x++) {
      const p = rowStart + x * 3
      const b = bmp[p]!
      const g = bmp[p + 1]!
      const r = bmp[p + 2]!
      // ITU-R 601 luma — same weights the G2 native converter uses.
      gray[y * width + x] = (r * 299 + g * 587 + b * 114) / 1000
    }
  }

  return encodeBmpBase64(gray, width, height)
}

// ── CLI ──────────────────────────────────────────────────────────────────
if (import.meta.main) {
  const input = process.argv[2]
  const size = process.argv[3] ? parseInt(process.argv[3], 10) : DEFAULT_SIZE
  if (!input) {
    console.error("usage: bun run png-to-bmp.ts <input.png> [size]")
    process.exit(1)
  }

  const base64 = await pngToGlassesBmp(input, size)

  const outTs = input.replace(/\.png$/i, "") + `.bmp.ts`
  const constName =
    "MAP_BMP_" +
    input
      .split("/")
      .pop()!
      .replace(/\.png$/i, "")
      .replace(/[^a-zA-Z0-9]/g, "_")
      .toUpperCase()

  const contents =
    `// AUTO-GENERATED by png-to-bmp.ts from ${input} at ${size}×${size}.\n` +
    `// Base64 8-bit grayscale BMP — data for a session.display.render() image element.\n` +
    `export const ${constName} = "${base64}"\n` +
    `export const ${constName}_SIZE = ${size}\n`

  await Bun.write(outTs, contents)
  console.log(`✓ ${input} → ${outTs}`)
  console.log(`  const: ${constName}  (${size}×${size}, ${(base64.length / 1024).toFixed(1)} KB base64)`)
}
