package com.mentra.asg_client.service.utils;

import java.util.UUID;

/**
 * Identity of this asg_client process on the wire.
 *
 * <p>The phone-BES BLE link survives an asg_client process restart (APK OTA, crash
 * recovery), so the phone cannot detect the restart from transport state — the old
 * failure mode was a phone waiting forever on a session that no longer existed
 * (incident rep_01KY6BJ0B7A4RBMQ7VN39KAE5E). Carrying this id in {@code glasses_ready}
 * and {@code version_info_1} makes session identity an explicit protocol property: the
 * phone re-runs its readiness flow whenever the id it observes changes — including the
 * first appearance of an id after an update from a build that predates the field.
 *
 * <p>Endpoint-to-endpoint by design: the BES relays these payloads opaquely, so no
 * firmware coordination is required.
 */
public final class ProcessSessionId {

    /** Stable for the life of this process; regenerated by every restart. */
    public static final String SID = UUID.randomUUID().toString().substring(0, 8);

    private ProcessSessionId() {}
}
