/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single source of truth for the tenir WebSocket message contract between the clients (TS) and the FastAPI api (Python). TS types and Pydantic models are generated from this file; do not hand-edit the generated outputs. Audio is sent as raw BINARY WebSocket frames (16kHz, signed 16-bit little-endian, mono PCM); every JSON frame below is a control or result message.
 */
export type TenirWsMessages = ClientMessage | ServerMessage;
export type ClientMessage = SessionStart | MicSwitch | SessionEnd | Ping;
/**
 * Which microphone the client is currently capturing from.
 */
export type MicSource = "g2-microphone" | "phone-microphone";
/**
 * Languages the STT engine may detect/report on captions.
 */
export type Lang = "en" | "es" | "fr" | "de" | "pt" | "it";
export type ServerMessage =
  | SessionReady
  | CaptionPartial
  | CaptionFinal
  | Cue
  | Translation
  | TranslationDone
  | Song
  | SongSync
  | SongDone
  | Pong
  | ErrorMessage;

/**
 * Client -> server. Opens a live session before any audio frames are sent.
 */
export interface SessionStart {
  type: "session.start";
  /**
   * Optional client-provided id to resume a dropped session; the server echoes the authoritative id in session.ready.
   */
  sessionId?: string;
  micSource: MicSource;
  sourceLang?: Lang;
}
/**
 * Client -> server. Runtime microphone source change.
 */
export interface MicSwitch {
  type: "mic.switch";
  micSource: MicSource;
}
/**
 * Client -> server. Finalizes the session; the transcript and retained audio are persisted.
 */
export interface SessionEnd {
  type: "session.end";
}
/**
 * Client -> server. Liveness probe; server replies with Pong.
 */
export interface Ping {
  type: "ping";
  /**
   * Client send timestamp (ms epoch), echoed back.
   */
  t?: number;
}
/**
 * Server -> client. Session accepted; client may begin streaming audio.
 */
export interface SessionReady {
  type: "session.ready";
  sessionId: string;
  resumed?: boolean;
}
/**
 * Server -> client. Fast, unstable hypothesis for the live caption band.
 */
export interface CaptionPartial {
  type: "caption.partial";
  text: string;
  lang?: Lang;
}
/**
 * Server -> client. Stable finalized segment with timing.
 */
export interface CaptionFinal {
  type: "caption.final";
  segmentId: string;
  text: string;
  lang?: Lang;
  startMs: number;
  endMs: number;
  words?: Word[];
}
export interface Word {
  text: string;
  startMs: number;
  endMs: number;
  confidence?: number;
}
/**
 * Server -> client. A private contextual info card the api derived from the live conversation (e.g. someone asks how far the sun is; the answer appears). Cues are private to the listener, not part of the conversation. Clients show it in a bordered box above the live transcript for ~10s, and persist it inline in the transcript history at atMs.
 */
export interface Cue {
  type: "cue";
  /**
   * Stable id for this cue (dedupe / popup keying).
   */
  cueId: string;
  /**
   * 1-3 word label for the cue box.
   */
  title: string;
  /**
   * The contextual detail shown in the box / history popup.
   */
  body: string;
  /**
   * Position on the conversation timeline (ms) the cue relates to, so history can render it inline where it appeared.
   */
  atMs: number;
  /**
   * Short label of the live source the cue's fact was grounded in (XERK-120), e.g. "BBC News" or "Wikipedia". Absent when the cue rests on the model's own knowledge; clients render it as a quiet attribution line under the body.
   */
  source?: string;
}
/**
 * Server -> client. English translation of one finalized non-English turn (XERK-160). Delivered off the caption path once the turn's caption.final is out; clients pair it with that segment by segmentId (web/mobile/phone render it alongside the original turn, the glasses lens shows it in the cue box slot). While a translation run is live the api suppresses cues; the run ends with translation.done.
 */
export interface Translation {
  type: "translation";
  /**
   * The caption.final segment this translates.
   */
  segmentId: string;
  /**
   * The English translation of the segment's text.
   */
  text: string;
  sourceLang?: Lang;
}
/**
 * Server -> client. The non-English run is over — the speaker is done being spoken-to in another language (an English turn arrived, or speech went quiet past the hold window). On the glasses this is what starts the translation box's 10s dismiss countdown; cue generation resumes after this.
 */
export interface TranslationDone {
  type: "translation.done";
}
/**
 * Server -> client. A song was recognized playing in the room (XERK-184). Clients show its time-synced lyrics in the same box a cue uses — title 'SONG NAME - ARTIST' over a body that auto-scrolls as the song plays. The scroll is driven client-side from an anchor: at session-timeline `atMs` the song was at `offsetMs` into the track, so the current line at wall-time t is the last line whose (song) atMs <= offsetMs + (t - atMs). A run of the same song is refreshed by `song.sync` and ended by `song.done`. While a song run is live the api suppresses cues, exactly as a translation run does.
 */
export interface Song {
  type: "song";
  /**
   * Stable id for this recognized-song run (keys song.sync / song.done / dedupe / history).
   */
  songId: string;
  /**
   * The song's title.
   */
  title: string;
  /**
   * The performing artist; the box title renders 'TITLE - ARTIST'.
   */
  artist: string;
  /**
   * The session-timeline position (ms) this anchor was measured at — where the song is placed in history, and the reference the client scrolls from.
   */
  atMs: number;
  /**
   * How far into the SONG (ms) the track was at `atMs` — the sync anchor. Paired with atMs it maps wall-clock to song position.
   */
  offsetMs: number;
  /**
   * The track's total length (ms), when known; lets the client bound the scroll.
   */
  durationMs?: number;
  /**
   * The full time-synced lyrics (LRC), ordered by song time. Empty when no synced lyrics were found (the client shows the title without a scroll).
   */
  lines: LyricLine[];
}
/**
 * One time-synced lyric line: the text and the timestamp (ms) it is sung at, measured from the START of the song (not the session).
 */
export interface LyricLine {
  /**
   * Offset into the SONG (ms) at which this line is sung — the LRC timestamp.
   */
  atMs: number;
  /**
   * The lyric line (may be empty for an instrumental gap).
   */
  text: string;
}
/**
 * Server -> client. A fresh sync anchor for a song already delivered (XERK-184): a periodic re-identification of the same run, so the client can correct drift between its local clock and the actual playback position. Carries no lyrics — same songId, same lines, new (atMs, offsetMs).
 */
export interface SongSync {
  type: "song.sync";
  /**
   * The run this re-anchors (matches the Song's songId).
   */
  songId: string;
  /**
   * Session-timeline position of the fresh anchor.
   */
  atMs: number;
  /**
   * Song position (ms) at the fresh anchor.
   */
  offsetMs: number;
}
/**
 * Server -> client. The recognized song is over — it stopped matching past the hold window, or a different song took over (XERK-184). On the glasses this starts the song box's dismiss countdown, mirroring translation.done; cue generation resumes after it.
 */
export interface SongDone {
  type: "song.done";
  /**
   * The run that ended.
   */
  songId: string;
}
/**
 * Server -> client. Reply to Ping.
 */
export interface Pong {
  type: "pong";
  /**
   * Echoed client timestamp from Ping.
   */
  t?: number;
}
/**
 * Server -> client. Recoverable or fatal error for the current session.
 */
export interface ErrorMessage {
  type: "error";
  code: "bad_request" | "unauthorized" | "session_not_found" | "rate_limited" | "internal";
  message: string;
  fatal?: boolean;
}
