// services/integrations/linear.service.ts
// Linear integration for bug report ticket creation and deduplication

import { LinearClient, Issue } from "@linear/sdk";
import { LLMProvider } from "@mentra/utils";
import { logger as rootLogger } from "../logging/pino-logger";
import type { IncidentLogs } from "../storage/incident-storage.service";

const logger = rootLogger.child({ service: "linear" });

// Linear configuration
const LINEAR_API_KEY = process.env.LINEAR_API_KEY;
const LINEAR_TEAM_ID = process.env.LINEAR_TEAM_ID;

/**
 * Bug summary generated by LLM analysis.
 */
export interface BugSummary {
  title: string;
  description: string;
  affectedComponents: string[];
  severity: "low" | "medium" | "high" | "critical";
  // Original user feedback (preserved for Linear tickets)
  expectedBehavior?: string;
  actualBehavior?: string;
  userSeverityRating?: number;
  // System info snapshot
  systemInfo?: {
    appVersion?: string;
    platform?: string;
    deviceName?: string;
    osVersion?: string;
    glassesConnected?: boolean;
    defaultWearable?: string;
    backendUrl?: string;
  };
}

/**
 * Result of creating or updating a Linear issue.
 */
export interface LinearResult {
  issueId: string;
  issueUrl: string;
  isNewIssue: boolean;
}

/**
 * Get date 30 days ago for Linear queries.
 */
function thirtyDaysAgo(): Date {
  const date = new Date();
  date.setDate(date.getDate() - 30);
  return date;
}

/**
 * Parse LLM response into structured BugSummary.
 */
function parseBugSummary(response: string): BugSummary {
  const lines = response.split("\n").filter(Boolean);

  // Extract title from first line
  const title =
    lines[0]
      ?.replace(/^(title:|1\.|#|\*\*title\*\*:?)/i, "")
      .trim()
      .slice(0, 80) || "Bug report";

  // Extract severity if present in response
  let severity: BugSummary["severity"] = "medium";
  const severityMatch = response.match(/severity[:\s]*(low|medium|high|critical)/i);
  if (severityMatch) {
    severity = severityMatch[1].toLowerCase() as BugSummary["severity"];
  }

  // Extract affected components
  const componentsMatch = response.match(/components?[:\s]*(.+)/i);
  const affectedComponents: string[] = [];
  if (componentsMatch) {
    affectedComponents.push(
      ...componentsMatch[1]
        .split(/[,;]/)
        .map((c) => c.trim())
        .filter(Boolean),
    );
  }

  // Build description from remaining lines
  const descriptionLines = lines
    .slice(1)
    .filter(
      (line) =>
        !line.toLowerCase().includes("severity") &&
        !line.toLowerCase().includes("component") &&
        !line.toLowerCase().startsWith("title"),
    );
  const description = descriptionLines.join(" ").trim() || "See logs for details";

  return {
    title,
    description: description.slice(0, 500),
    affectedComponents,
    severity,
  };
}

/**
 * Generate a bug summary using LLM analysis of incident logs.
 */
export async function generateBugSummary(incident: IncidentLogs): Promise<BugSummary> {
  const llm = LLMProvider.getLLM({ temperature: 0.3, maxTokens: 500 });

  // Extract relevant error/warning logs
  const phoneErrors = (incident.phoneLogs || [])
    .filter((l) => ["error", "warn"].includes(l.level))
    .slice(-30)
    .map((l) => `[${l.source || "phone"}] ${l.message}`)
    .join("\n");

  const cloudErrors = (incident.cloudLogs || [])
    .filter((l) => ["error", "warn"].includes(l.level))
    .slice(-30)
    .map((l) => `[${l.source || "cloud"}] ${l.message}`)
    .join("\n");

  const feedback = incident.feedback as Record<string, unknown>;

  const prompt = `Analyze this bug report and logs. Generate:
1. A concise title (max 80 chars) that describes the issue
2. A brief description of the likely root cause
3. Affected components (e.g., "BLE", "Audio", "WebSocket", "UI")
4. Severity (low/medium/high/critical)

User's bug report:
Expected behavior: ${feedback?.expectedBehavior || "Not specified"}
Actual behavior: ${feedback?.actualBehavior || "Not specified"}
User severity rating: ${feedback?.severityRating || "Not specified"}/5

Phone state at time of report:
- Glasses connected: ${incident.phoneState?.glasses ? "Yes" : "No"}
- Running apps: ${JSON.stringify((feedback?.systemInfo as Record<string, unknown>)?.runningApps || [])}

Recent phone errors/warnings:
${phoneErrors || "(none)"}

Recent cloud errors/warnings:
${cloudErrors || "(none)"}

Format your response as:
Title: [concise title]
Description: [root cause analysis]
Components: [comma-separated list]
Severity: [low/medium/high/critical]`;

  // Extract system info from feedback
  const systemInfo = feedback?.systemInfo as BugSummary["systemInfo"] | undefined;

  try {
    const response = await llm.invoke(prompt);
    const content = typeof response.content === "string" ? response.content : JSON.stringify(response.content);
    const parsed = parseBugSummary(content);

    // Preserve original user feedback in the summary
    return {
      ...parsed,
      expectedBehavior: feedback?.expectedBehavior as string | undefined,
      actualBehavior: feedback?.actualBehavior as string | undefined,
      userSeverityRating: feedback?.severityRating as number | undefined,
      systemInfo,
    };
  } catch (err) {
    logger.warn({ error: err }, "LLM summary generation failed, using fallback");
    return {
      title: `Bug report: ${(feedback?.actualBehavior as string)?.slice(0, 60) || "Issue reported"}`,
      description: (feedback?.actualBehavior as string) || "See logs for details",
      affectedComponents: [],
      severity: "medium",
      expectedBehavior: feedback?.expectedBehavior as string | undefined,
      actualBehavior: feedback?.actualBehavior as string | undefined,
      userSeverityRating: feedback?.severityRating as number | undefined,
      systemInfo,
    };
  }
}

/**
 * Find a similar existing Linear issue using LLM matching.
 */
export async function findSimilarLinearIssue(linear: LinearClient, summary: BugSummary): Promise<Issue | null> {
  if (!LINEAR_TEAM_ID) {
    logger.warn("LINEAR_TEAM_ID not configured");
    return null;
  }

  try {
    // Get recent open bug issues
    const recentIssues = await linear.issues({
      filter: {
        team: { id: { eq: LINEAR_TEAM_ID } },
        state: { type: { in: ["backlog", "unstarted", "started"] } },
        createdAt: { gte: thirtyDaysAgo() },
      },
      first: 50,
    });

    if (recentIssues.nodes.length === 0) {
      return null;
    }

    const llm = LLMProvider.getLLM({ temperature: 0.1, maxTokens: 50 });

    const prompt = `Given this new bug:
Title: ${summary.title}
Description: ${summary.description}
Components: ${summary.affectedComponents.join(", ")}

Does it describe the SAME underlying issue as any of these existing tickets?
Only match if it's clearly the same root cause, not just similar symptoms.

Existing tickets:
${recentIssues.nodes.map((i, idx) => `${idx + 1}. [${i.identifier}] ${i.title}\n   ${i.description?.slice(0, 600) || ""}`).join("\n\n")}

Reply with ONLY the ticket identifier (e.g., "MEN-123") if there's a clear match, or "NONE" if this is a new/different issue.`;

    const response = await llm.invoke(prompt);
    const content = typeof response.content === "string" ? response.content : JSON.stringify(response.content);
    const match = content.trim().toUpperCase();

    if (match === "NONE" || !match) {
      return null;
    }

    // Find the matching issue
    const matchedIssue = recentIssues.nodes.find((i) => i.identifier.toUpperCase() === match);

    if (matchedIssue) {
      logger.info({ identifier: matchedIssue.identifier }, "Found similar existing issue");
    }

    return matchedIssue || null;
  } catch (err) {
    logger.warn({ error: err }, "Failed to search for similar issues");
    return null;
  }
}

/**
 * Create a new Linear issue or add a comment to an existing one.
 */
export async function createOrUpdateLinearIssue(
  incidentId: string,
  summary: BugSummary,
  consoleUrl: string,
): Promise<LinearResult | null> {
  if (!LINEAR_API_KEY || !LINEAR_TEAM_ID) {
    logger.warn(
      {
        hasApiKey: !!LINEAR_API_KEY,
        hasTeamId: !!LINEAR_TEAM_ID,
      },
      "Linear not configured - skipping ticket creation",
    );
    return null;
  }

  const linear = new LinearClient({ apiKey: LINEAR_API_KEY });

  try {
    // Check for similar existing issue
    const similarIssue = await findSimilarLinearIssue(linear, summary);

    if (similarIssue) {
      // Build system info line for comment
      const sys = summary.systemInfo;
      const commentSysInfoParts: string[] = [];
      if (sys) {
        if (sys.appVersion) commentSysInfoParts.push(`App: ${sys.appVersion}`);
        if (sys.platform) commentSysInfoParts.push(`Platform: ${sys.platform}`);
        if (sys.deviceName) commentSysInfoParts.push(`Device: ${sys.deviceName}`);
        commentSysInfoParts.push(`Glasses: ${sys.glassesConnected ? "Connected" : "Disconnected"}`);
        if (sys.backendUrl) commentSysInfoParts.push(`Backend: ${sys.backendUrl}`);
      }
      const systemInfoLine = commentSysInfoParts.length > 0 ? commentSysInfoParts.join(" | ") : null;

      // Add comment to existing issue
      await linear.createComment({
        issueId: similarIssue.id,
        body: `**New occurrence reported**

Incident ID: \`${incidentId}\`

**Expected:** ${summary.expectedBehavior || "Not specified"}
**Actual:** ${summary.actualBehavior || "Not specified"}
${systemInfoLine ? `**System:** ${systemInfoLine}` : ""}

[View incident logs](${consoleUrl})`,
      });

      logger.info(
        {
          incidentId,
          issueId: similarIssue.id,
          identifier: similarIssue.identifier,
        },
        "Added comment to existing Linear issue",
      );

      return {
        issueId: similarIssue.id,
        issueUrl: similarIssue.url,
        isNewIssue: false,
      };
    }

    // Build system info line
    const sys = summary.systemInfo;
    const systemInfoParts: string[] = [];
    if (sys) {
      if (sys.appVersion) systemInfoParts.push(`App: ${sys.appVersion}`);
      if (sys.platform) systemInfoParts.push(`Platform: ${sys.platform}`);
      if (sys.deviceName) systemInfoParts.push(`Device: ${sys.deviceName}`);
      if (sys.osVersion) systemInfoParts.push(`OS: ${sys.osVersion}`);
      systemInfoParts.push(`Glasses: ${sys.glassesConnected ? "Connected" : "Disconnected"}`);
      if (sys.defaultWearable) systemInfoParts.push(`Wearable: ${sys.defaultWearable}`);
      if (sys.backendUrl) systemInfoParts.push(`Backend: ${sys.backendUrl}`);
    }
    const systemInfoLine = systemInfoParts.length > 0 ? systemInfoParts.join(" | ") : null;

    // Create new issue
    const issue = await linear.createIssue({
      teamId: LINEAR_TEAM_ID,
      title: summary.title,
      description: `${summary.description}

## User Report

**Expected:** ${summary.expectedBehavior || "Not specified"}

**Actual:** ${summary.actualBehavior || "Not specified"}

**User Severity:** ${summary.userSeverityRating !== undefined ? `${summary.userSeverityRating}/5` : "Not rated"}

## Details

- **Incident ID:** \`${incidentId}\`
${systemInfoLine ? `- **System Info:** ${systemInfoLine}` : ""}

[View incident logs](${consoleUrl})`,
      priority: severityToPriority(summary.severity),
    });

    const createdIssue = await issue.issue;
    if (!createdIssue) {
      throw new Error("Failed to create issue - no issue returned");
    }

    logger.info(
      {
        incidentId,
        issueId: createdIssue.id,
        identifier: createdIssue.identifier,
      },
      "Created new Linear issue",
    );

    return {
      issueId: createdIssue.id,
      issueUrl: createdIssue.url,
      isNewIssue: true,
    };
  } catch (err) {
    logger.error({ error: err, incidentId }, "Failed to create/update Linear issue");
    return null;
  }
}

/**
 * Convert severity to Linear priority (1=urgent, 2=high, 3=medium, 4=low).
 */
function severityToPriority(severity: BugSummary["severity"]): number {
  switch (severity) {
    case "critical":
      return 1;
    case "high":
      return 2;
    case "medium":
      return 3;
    case "low":
      return 4;
    default:
      return 3;
  }
}
